compressionLevel: mixed

enableGlobalCache: false

enableMirror: false

enableTelemetry: false

logFilters:
  - code: YN0013
    level: discard

nodeLinker: node-modules

packageExtensions:
  "@types/node@*":
    dependencies:
      undici-types: "*"
