nodeLinker: node-modules

enableGlobalCache: false

enableTelemetry: false

packageExtensions:
  "@types/node@*":
    dependencies:
      undici-types: "*"

compressionLevel: mixed

enableMirror: false

logFilters:
  - code: YN0013
    level: discard 