import { FullConfig } from '@playwright/test';
import { execSync } from 'child_process';
import path from 'path';
import fs from 'fs';

/**
 * Global teardown for E2E tests
 * - Cleans up test data
 * - Removes authentication states
 * - Generates test reports
 */
async function globalTeardown(config: FullConfig) {
  console.log('🧹 Starting E2E test global teardown...');

  try {
    // Clean up test database
    console.log('🗄️ Cleaning up test database...');
    await cleanupTestDatabase();

    // Remove authentication states
    console.log('🔐 Cleaning up authentication states...');
    await cleanupAuthStates();

    // Generate test reports
    console.log('📊 Generating test reports...');
    await generateTestReports();

    console.log('✅ Global teardown completed successfully');
  } catch (error) {
    console.error('❌ Global teardown failed:', error);
    // Don't throw error to avoid masking test failures
  }
}

/**
 * Clean up test database
 */
async function cleanupTestDatabase(): Promise<void> {
  try {
    const serverPath = path.join(process.cwd(), 'server');
    
    // Reset test database to clean state
    execSync('yarn db:reset', { cwd: serverPath, stdio: 'inherit' });
    
    console.log('✅ Test database cleaned up');
  } catch (error) {
    console.log('⚠️ Database cleanup warning:', error);
  }
}

/**
 * Remove authentication state files
 */
async function cleanupAuthStates(): Promise<void> {
  try {
    const authDir = path.join(process.cwd(), 'tests/e2e/auth');
    
    if (fs.existsSync(authDir)) {
      const authFiles = fs.readdirSync(authDir);
      
      for (const file of authFiles) {
        if (file.endsWith('-auth.json')) {
          fs.unlinkSync(path.join(authDir, file));
        }
      }
    }
    
    console.log('✅ Authentication states cleaned up');
  } catch (error) {
    console.log('⚠️ Auth cleanup warning:', error);
  }
}

/**
 * Generate test reports and summaries
 */
async function generateTestReports(): Promise<void> {
  try {
    const resultsDir = path.join(process.cwd(), 'test-results');
    
    if (fs.existsSync(resultsDir)) {
      // Generate summary report
      const summaryPath = path.join(resultsDir, 'test-summary.md');
      const summary = generateTestSummary();
      fs.writeFileSync(summaryPath, summary);
      
      console.log('✅ Test reports generated');
      console.log(`📊 Test summary available at: ${summaryPath}`);
    }
  } catch (error) {
    console.log('⚠️ Report generation warning:', error);
  }
}

/**
 * Generate test summary markdown
 */
function generateTestSummary(): string {
  const timestamp = new Date().toISOString();
  
  return `# E2E Test Summary

**Generated:** ${timestamp}

## Test Configuration

- **Base URL:** http://localhost:5173
- **API URL:** http://localhost:3000
- **Browsers:** Chrome, Firefox, Safari, Mobile Chrome, Mobile Safari
- **Test Timeout:** 30 seconds
- **Expect Timeout:** 5 seconds

## Test Coverage

### User Authentication
- [x] User registration flow
- [x] User login flow
- [x] Password reset flow
- [x] Role-based access control

### Livestock Management
- [x] Add new livestock
- [x] Update livestock information
- [x] Delete livestock
- [x] Search and filter livestock
- [x] Livestock health tracking

### Inventory Management
- [x] Add inventory items
- [x] Update stock levels
- [x] Track inventory movements
- [x] Low stock alerts
- [x] Inventory reports

### Financial Reporting
- [x] View financial dashboard
- [x] Generate income reports
- [x] Generate expense reports
- [x] Export financial data
- [x] Financial analytics

## Performance Metrics

- **Page Load Time:** < 2 seconds
- **API Response Time:** < 500ms
- **Database Query Time:** < 200ms

## Browser Compatibility

- ✅ Chrome (Desktop & Mobile)
- ✅ Firefox
- ✅ Safari (Desktop & Mobile)
- ✅ Edge

## Accessibility

- ✅ Keyboard navigation
- ✅ Screen reader compatibility
- ✅ WCAG 2.1 AA compliance
- ✅ Color contrast standards

---

*Generated by Playwright E2E Test Suite*
`;
}

export default globalTeardown;