export declare const formatDate: (date: Date | string, format?: string) => string;
export declare const parseDate: (dateString: string) => Date | null;
export declare const isValidDate: (date: any) => boolean;
export declare const addDays: (date: Date, days: number) => Date;
export declare const diffInDays: (date1: Date, date2: Date) => number;
export declare const isToday: (date: Date) => boolean;
export declare const isExpired: (date: Date) => boolean;
export declare const capitalize: (str: string) => string;
export declare const capitalizeWords: (str: string) => string;
export declare const slugify: (str: string) => string;
export declare const generateCode: (prefix?: string, length?: number) => string;
export declare const truncate: (str: string, maxLength: number, suffix?: string) => string;
export declare const formatNumber: (num: number, decimals?: number) => string;
export declare const formatCurrency: (amount: number, currency?: string) => string;
export declare const calculatePercentage: (value: number, total: number) => number;
export declare const roundToDecimals: (num: number, decimals?: number) => number;
export declare const clamp: (value: number, min: number, max: number) => number;
export declare const unique: <T>(array: T[]) => T[];
export declare const groupBy: <T, K extends keyof T>(array: T[], key: K) => Record<string, T[]>;
export declare const sortBy: <T>(array: T[], key: keyof T, order?: "asc" | "desc") => T[];
export declare const chunk: <T>(array: T[], size: number) => T[][];
export declare const omit: <T extends Record<string, any>, K extends keyof T>(obj: T, keys: K[]) => Omit<T, K>;
export declare const pick: <T extends Record<string, any>, K extends keyof T>(obj: T, keys: K[]) => Pick<T, K>;
export declare const isEmpty: (value: any) => boolean;
export declare const deepClone: <T>(obj: T) => T;
export declare const isValidEmail: (email: string) => boolean;
export declare const isValidPhone: (phone: string) => boolean;
export declare const isValidUrl: (url: string) => boolean;
export declare const validateRequired: (value: any, fieldName: string) => string | null;
export declare const validateMinLength: (value: string, min: number, fieldName: string) => string | null;
export declare const validateMaxLength: (value: string, max: number, fieldName: string) => string | null;
export declare const validateMinValue: (value: number, min: number, fieldName: string) => string | null;
export declare const validateMaxValue: (value: number, max: number, fieldName: string) => string | null;
export declare const formatFileSize: (bytes: number) => string;
export declare const getFileExtension: (filename: string) => string;
export declare const getMimeTypeFromExtension: (extension: string) => string;
export declare const hexToRgb: (hex: string) => {
    r: number;
    g: number;
    b: number;
} | null;
export declare const rgbToHex: (r: number, g: number, b: number) => string;
export declare const getContrastColor: (hex: string) => string;
export declare const calculateFeedConversionRatio: (feedConsumed: number, weightGain: number) => number;
export declare const calculateProductionRate: (eggsProduced: number, totalBirds: number) => number;
export declare const calculateMortalityRate: (deaths: number, totalAnimals: number) => number;
export declare const calculateProfitMargin: (revenue: number, costs: number) => number;
export declare const calculateStockingDensity: (fishCount: number, pondVolume: number) => number;
export declare const calculateBMI: (weight: number, height: number) => number;
declare const _default: {
    formatDate: (date: Date | string, format?: string) => string;
    parseDate: (dateString: string) => Date | null;
    isValidDate: (date: any) => boolean;
    addDays: (date: Date, days: number) => Date;
    diffInDays: (date1: Date, date2: Date) => number;
    isToday: (date: Date) => boolean;
    isExpired: (date: Date) => boolean;
    capitalize: (str: string) => string;
    capitalizeWords: (str: string) => string;
    slugify: (str: string) => string;
    generateCode: (prefix?: string, length?: number) => string;
    truncate: (str: string, maxLength: number, suffix?: string) => string;
    formatNumber: (num: number, decimals?: number) => string;
    formatCurrency: (amount: number, currency?: string) => string;
    calculatePercentage: (value: number, total: number) => number;
    roundToDecimals: (num: number, decimals?: number) => number;
    clamp: (value: number, min: number, max: number) => number;
    unique: <T>(array: T[]) => T[];
    groupBy: <T, K extends keyof T>(array: T[], key: K) => Record<string, T[]>;
    sortBy: <T>(array: T[], key: keyof T, order?: "asc" | "desc") => T[];
    chunk: <T>(array: T[], size: number) => T[][];
    omit: <T extends Record<string, any>, K extends keyof T>(obj: T, keys: K[]) => Omit<T, K>;
    pick: <T extends Record<string, any>, K extends keyof T>(obj: T, keys: K[]) => Pick<T, K>;
    isEmpty: (value: any) => boolean;
    deepClone: <T>(obj: T) => T;
    isValidEmail: (email: string) => boolean;
    isValidPhone: (phone: string) => boolean;
    isValidUrl: (url: string) => boolean;
    validateRequired: (value: any, fieldName: string) => string | null;
    validateMinLength: (value: string, min: number, fieldName: string) => string | null;
    validateMaxLength: (value: string, max: number, fieldName: string) => string | null;
    validateMinValue: (value: number, min: number, fieldName: string) => string | null;
    validateMaxValue: (value: number, max: number, fieldName: string) => string | null;
    formatFileSize: (bytes: number) => string;
    getFileExtension: (filename: string) => string;
    getMimeTypeFromExtension: (extension: string) => string;
    hexToRgb: (hex: string) => {
        r: number;
        g: number;
        b: number;
    } | null;
    rgbToHex: (r: number, g: number, b: number) => string;
    getContrastColor: (hex: string) => string;
    calculateFeedConversionRatio: (feedConsumed: number, weightGain: number) => number;
    calculateProductionRate: (eggsProduced: number, totalBirds: number) => number;
    calculateMortalityRate: (deaths: number, totalAnimals: number) => number;
    calculateProfitMargin: (revenue: number, costs: number) => number;
    calculateStockingDensity: (fishCount: number, pondVolume: number) => number;
    calculateBMI: (weight: number, height: number) => number;
};
export default _default;
//# sourceMappingURL=index.d.ts.map