import { Column, Entity, JoinColumn, ManyToOne } from 'typeorm';
import { BaseEntity } from './BaseEntity';
import { Farm } from './Farm';
import { InventoryItem } from './InventoryItem';
import { User } from './User';

export enum StockAlertType {
  LOW_STOCK = 'low_stock',
  OUT_OF_STOCK = 'out_of_stock',
  EXPIRY_WARNING = 'expiry_warning',
  EXPIRED = 'expired',
  OVERSTOCK = 'overstock',
}

export enum StockAlertSeverity {
  LOW = 'low',
  MEDIUM = 'medium',
  HIGH = 'high',
  CRITICAL = 'critical',
}

@Entity('stock_alerts')
export class StockAlert extends BaseEntity {
  @Column({ type: 'enum', enum: StockAlertType })
  alertType!: StockAlertType;

  @Column({ type: 'enum', enum: StockAlertSeverity })
  severity!: StockAlertSeverity;

  @Column({ type: 'varchar', length: 255 })
  title!: string;

  @Column({ type: 'text' })
  message!: string;

  @Column({ type: 'decimal', precision: 10, scale: 2 })
  currentStock!: number;

  @Column({ type: 'decimal', precision: 10, scale: 2, nullable: true })
  threshold?: number;

  @Column({ type: 'boolean', default: false })
  acknowledged!: boolean;

  @Column({ type: 'timestamp', nullable: true })
  acknowledgedAt?: Date;

  @Column({ type: 'boolean', default: false })
  resolved!: boolean;

  @Column({ type: 'timestamp', nullable: true })
  resolvedAt?: Date;

  @Column({ type: 'text', nullable: true })
  resolutionNotes?: string;

  @Column({ type: 'boolean', default: false })
  autoGenerated!: boolean;

  // Relationships
  @ManyToOne(() => InventoryItem, { nullable: false })
  @JoinColumn({ name: 'itemId' })
  item!: InventoryItem;

  @Column({ type: 'varchar', length: 255 })
  itemId!: string;

  @ManyToOne(() => Farm, { nullable: false })
  @JoinColumn({ name: 'farmId' })
  farm!: Farm;

  @Column({ type: 'varchar', length: 255 })
  farmId!: string;

  @ManyToOne(() => User, { nullable: true })
  @JoinColumn({ name: 'acknowledgedById' })
  acknowledgedBy?: User;

  @Column({ type: 'varchar', length: 255, nullable: true })
  acknowledgedById?: string;

  @ManyToOne(() => User, { nullable: true })
  @JoinColumn({ name: 'resolvedById' })
  resolvedBy?: User;

  @Column({ type: 'varchar', length: 255, nullable: true })
  resolvedById?: string;
}
